version: "3"
services:
  server:
    command: node index.js
    ports:
      - "4000:4000"
    build:
      context: ./server
      dockerfile: Dockerfile
  client:
    command: npm start
    ports:
      - "3000:3000"
    build:
      context: ./client
      dockerfile: Dockerfile
